[project]
name = "charlotte2-0"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lightning>=2.6.1",
    "torch>=2.10.0",
    "transformers>=5.2.0",
]
